### PR TITLE
fix https://get.scheme.org

### PR DESCRIPTION
**Pull request by spdegabrielle**
https://get.scheme.org is currently showing a blank page

### CODE REVIEW

**Review by arthurgleckler — CHANGES_REQUESTED** [review]
Thanks for the pull request.  Some of these implementations are not well-known.  It might be better to start from the list at https://www.scheme.org/, or at least with the union of the two lists.

**Comment by spdegabrielle** [comment]
went with the list at https://www.scheme.org/

really keen for https://get.scheme.org/ not to be blank. 
image

**Comment by arthurgleckler** [comment]
Wait, I merged this, but have you asked the Racket folks whether they want this?  We always check with the implementers first.

**Comment by arthurgleckler** [comment]
Sorry, I made that comment on the wrong pull request.  Please ignore here.

**Comment by arthurgleckler** [comment]
Thanks.  Merged and pushed.

**Pull request merged**
